# numpy

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4,5]

In [3]:
type(my_list)

list

In [4]:
arr=np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

In [8]:
# multidimentional array
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]

In [9]:
new_arr=np.array([my_list1,my_list2,my_list3])

In [10]:
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
new_arr.shape

(3, 5)

In [12]:
new_arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# indexing

In [13]:
# accessing elements in array
arr=np.array([1,2,3,4,5])

In [14]:
arr[3]

np.int64(4)

In [15]:
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
new_arr[0,3]

np.int64(4)

In [17]:
# for all row and colomn
new_arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
# for first 2 row and 2 colomn
new_arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [19]:
new_arr[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [20]:
new_arr[1:,1:3]

array([[ 7,  8],
       [12, 13]])

In [21]:
new_arr[1,1:4]

array([7, 8, 9])

# some inbuilt functionn in pandas 


In [22]:
arr=np.arange(0,10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr=np.arange(0,10,step=2)

In [25]:
arr

array([0, 2, 4, 6, 8])

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
## function and broadcasting 
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[3:]=100

In [29]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [30]:
arr1=arr

In [31]:
arr1[3:]=500
print(arr1)


[  0   1   2 500 500 500 500 500 500 500]


In [32]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [33]:
arr1=arr.copy()
arr1[3:]=1001
print(arr1)

[   0    1    2 1001 1001 1001 1001 1001 1001 1001]


In [34]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [35]:
arr=np.arange(1,11)

In [36]:
## some condition very  useful in exploratory data analysis 

In [37]:
val=2

In [38]:
arr<2

array([ True, False, False, False, False, False, False, False, False,
       False])

In [39]:
arr[arr<2]

array([1])

In [40]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
#creat array and reshape 
np.arange (1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
np.ones(4)

array([1., 1., 1., 1.])

In [43]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.random.rand(4,4,)

array([[0.38356718, 0.98316487, 0.20205931, 0.17749933],
       [0.64531664, 0.78703247, 0.55094813, 0.44916337],
       [0.36430013, 0.7201382 , 0.66407127, 0.51976099],
       [0.46409588, 0.56847032, 0.14833046, 0.79854695]])

In [45]:
np.random.randint(0,25,(4,4))

array([[20,  6, 14, 21],
       [ 3, 23, 14,  3],
       [ 9,  4, 12, 12],
       [21, 24, 17,  0]], dtype=int32)