# numpy

In [16]:
import numpy as np

In [17]:
my_list=[1,2,3,4,5]

In [18]:
type(my_list)

list

In [19]:
arr=np.array(my_list)

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr.shape

(5,)

In [23]:
# multidimentional array
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]

In [24]:
new_arr=np.array([my_list1,my_list2,my_list3])

In [25]:
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
new_arr.shape

(3, 5)

In [27]:
new_arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# indexing

In [28]:
# accessing elements in array
arr=np.array([1,2,3,4,5])

In [29]:
arr[3]

np.int64(4)

In [31]:
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
new_arr[0,3]

np.int64(4)

In [32]:
# for all row and colomn
new_arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
# for first 2 row and 2 colomn
new_arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [36]:
new_arr[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [37]:
new_arr[1:,1:3]

array([[ 7,  8],
       [12, 13]])

In [38]:
new_arr[1,1:4]

array([7, 8, 9])

# some inbuilt functionn in pandas 


In [39]:
arr=np.arange(0,10)

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr=np.arange(0,10,step=2)

In [42]:
arr

array([0, 2, 4, 6, 8])

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
## function and broadcasting 
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[3:]=100

In [46]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [47]:
arr1=arr

In [49]:
arr1[3:]=500
print(arr1)


[  0   1   2 500 500 500 500 500 500 500]


In [50]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [52]:
arr1=arr.copy()
arr1[3:]=1001
print(arr1)

[   0    1    2 1001 1001 1001 1001 1001 1001 1001]


In [53]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [55]:
arr=np.arange(1,11)

In [54]:
## some condition very  useful in exploratory data analysis 

In [56]:
val=2

In [57]:
arr<2

array([ True, False, False, False, False, False, False, False, False,
       False])

In [60]:
arr[arr<2]

array([1])

In [58]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [61]:
#creat array and reshape 
np.arange (1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [63]:
np.ones(4)

array([1., 1., 1., 1.])

In [65]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
np.random.rand(4,4,)

array([[0.02919897, 0.43017468, 0.61173459, 0.76114634],
       [0.06664495, 0.87213216, 0.49766634, 0.38138175],
       [0.30983374, 0.71251049, 0.75211661, 0.35985799],
       [0.11742246, 0.49403138, 0.00154937, 0.34126873]])

In [70]:
np.random.randint(0,25,(4,4))

array([[16, 12,  1, 16],
       [ 9,  5,  0,  0],
       [15, 17, 22, 23],
       [15,  2, 13, 18]], dtype=int32)